apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "elife-xpub.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "elife-xpub.name" . }}
    helm.sh/chart: {{ include "elife-xpub.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: app
    app.kubernetes.io/part-of: {{ include "elife-xpub.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "elife-xpub.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "elife-xpub.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: app
    app.kubernetes.io/part-of: {{ include "elife-xpub.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: NODE_ENV
            value: production
          - name: PUBSWEET_SECRET
            value: example-secret
          command: ["node", "app"]
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
