image:
  repository: elifesciences/elife-xpub
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

##
## Postgresql chart configuration
##
postgresql:
  image:
    # should be 10.4 but it's the closest we have from bitnami/postgresql
    tag: "10.5.0"
  persistence:
    enabled: false
  postgresqlDatabase: test
  postgresqlUsername: test
  postgresqlPassword: pw
